//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLoja.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente : IComparable<Cliente>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compras = new HashSet<Compra>();
        }
    
        public int codCliente { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public string telefone { get; set; }
        public string endereco { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public System.DateTime dtNascimento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compras { get; set; }


        public int CompareTo(Cliente outroCLiente)
        {
            return this.nome.CompareTo(outroCLiente.nome);
        }
    }
}
