//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLoja.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Produto
    {
        public int codProduto { get; set; }
        public int codCompra { get; set; }
        public int qtde_comprada { get; set; }
        public float valor_comprado { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
