//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLoja.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra : IComparable<Compra>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Compra_Produto = new HashSet<Compra_Produto>();
        }
    
        public int codCompra { get; set; }
        public System.DateTime dataCompra { get; set; }
        public int codCliente { get; set; }
        public int codVendedor { get; set; }
        public float valor_total { get; set; }

        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Produto> Compra_Produto { get; set; }
        public virtual Vendedor Vendedor { get; set; }

        public int CompareTo(Compra compra)
        {
            if (this.valor_total > compra.valor_total)
                return -1;

            if (this.valor_total < compra.valor_total)
                return 1;

            return this.valor_total.CompareTo(compra.valor_total);

        }
    }
}
